services:
  - type: web
    name: my-flask-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: BREVO_SMTP_LOGIN
        sync: false
      - key: BREVO_SMTP_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
